### PR TITLE
pushed opensuse patch rubygem-passenger-4.0.14_missing_includes.patch

### PR DESCRIPTION
**Pull request by darix**
This patch fixed a build problem for us.

### CODE REVIEW

**Comment by OnixGH** [comment]
@darix Can you comment on this? I'm afraid we can't do anything with this pull request otherwise :(

**Comment by darix** [comment]
uhm i need to retest again. but 5.0.5 building fails in something libev related. can someone ping me on freenode for faster turnaround?

**Comment by OnixGH** [comment]
I'm not on IRC myself, but 5.0.6 was released today. If you find a good moment to test it would be best to post your build error and platform info so we can have multiple pairs of eyes on it.

**Comment by darix** [comment]
let me grab 5.0.6

**Comment by darix** [comment]
https://files.nordisch.org/passenger/buildlog.without.include.patch.opensuse_13.2.txt

vs

https://files.nordisch.org/passenger/buildlog.opensuse_13.2.txt

but atm they both fail with:

```
ext/common/SafeLibev.h:148:55: error: 'ev_loop_get_pipe' was not declared in this scope
```

**Comment by darix** [comment]
source for rpm here: https://build.opensuse.org/package/show/home:darix:ruby/rubygem-passenger

**Comment by FooBarWidget** [comment]
@darix We've forked libev because we need some features not found in upstream. So since version 5.0.5, it is no longer possible to compile Passenger against the upstream libev. You must use our bundled version.

**Comment by darix** [comment]
maybe make extconf.rb fail if someone tries to use the system copy?

**Comment by darix** [comment]
ok disabled the patch and it really seems with 5.0.6 it isnt needed anymore.

**Pull request closed without merging**
