### PR TITLE
Fast way to get child UID

### PR DESCRIPTION
**Pull request by plmnikulin**
Optimize smart spawn a bit.
Using `ProcessMetricsCollector` with `ps` subprocess
just to get process UID is an overkill. `stat()`
allows to avoid fork and requires less error handling.

### CODE REVIEW

**Comment by plmnikulin** [comment]
Maybe I have miss some portability issue that `ps` allows to overcome, so fill free to decline the pull request.

As an additional note, `ps -pPID` in src/cxx_supportlib/SystemTools/ProcessMetricsCollector.h walks through all `/proc/PID` directories. There is an option `--quick-pid/-q` that reads info for specified PIDs only. Again unsure if it is available everywhere.

**Comment by CamJN** [comment]
Sorry procfs is not available on all of our supported platforms, so I cannot accept this as is.

**Comment by plmnikulin** [comment]
No problem with rejecting of this patch operating of procfs directly.
Is support of `--quick-pid/-q` `ps` options is limited to platforms having procfs as well? Currently on linux `ps -pPID` walks through all process directories in `/proc` since `-p` is just a filter.

**Comment by plmnikulin** [comment]
Maybe it could be used as an alternative strategy configured at build time but I have no plans to continue work on this pull request

**Pull request closed without merging**
