### PR TITLE
Replace imp module with importlib

### PR DESCRIPTION
**Pull request by rongxin-liu**
This PR addresses https://github.com/phusion/passenger/issues/2501

### CODE REVIEW

**Comment by CamJN** [comment]
Please sign the [contributor agreement](https://www.phusion.nl/forms/contributor_agreement).

**Comment by rongxin-liu** [comment]
> contributor agreement

I submitted the form.

Thank you!

**Comment by raydleemsc** [comment]
This hasn't reached the  docker images for v2.5.1 yet, even though the app states it is v6.0.18

**Comment by CamJN** [comment]
@raydleemsc the fix is in passenger 6.0.19 which isn't released yet due to difficulty with our CI. once Passenger 6.0.19 is out, then I will make a docker image release with that passenger version.

**Pull request merged**
