### PR TITLE
Node loader linting

### PR DESCRIPTION
**Pull request by dr-dimitru**
We're working on highly efficient micro-services which handles hundred thousands of requests per second. Phusion Passenger is great tool for nodejs apps, thank you for this.

During optimisation process the idea to check sources related to nodejs in Phusion Passenger come to mind. We prefer always `strict mode` and strict linting/formatting for our code.

We have run our pre-publish tools over your nodejs related code. And came up with this PR:

node-loader.js
 - Minor indentation and mixed spaces/tabs indentation fix
 - Move `doListen` and `doneListening` out of `installServer` function scope

ustrouter_connector.js
 - `i` is not defined in various `for` loops
 - define other not defined variables
 - Minor indentation and mixed spaces/tabs indentation fix

ustreporter.js
 - Missed semicolons

log_mongodb.js
 - `i` is not defined in `for` loops
 - Various missed semicolons
 - `friendlyName` defined but never used

log_express.js
 - Missed semicolons

line_reader.js
 - Missed semicolons
 - Unused variables

Changes was tested on Dev and Prod environments.

### CODE REVIEW

**Comment by FooBarWidget** [comment]
Thank you for letting us know and for running this check.

**Comment by OnixGH** [comment]
@dr-dimitru to integrate it directly we need a signed [contributor agreement](https://www.phusion.nl/contributor), could you have a look at that?

The commits look good to me, thanks for splitting them up, and awesome that you tested them in prod. The only minor remark I have is that removed (unused) imports are not mentioned in the comments.

Can you squash the commits into one for the final merge?

**Comment by dr-dimitru** [comment]
Hello @OnixGH ,

Agreement Signed and sent to Phusion email address.

> The commits look good to me, thanks for splitting them up, and awesome that you tested them in prod. The only minor remark I have is that removed (unused) imports are not mentioned in the comments.

Sure I can address that changes too.

node-loader.js
 - `net` module required, but not used

ustrouter_connector.js
 - `os` module required, but not used

> Can you squash the commits into one for the final merge?

Not sure how I may done this. Only If I create a new branch and new PR?

**Comment by OnixGH** [comment]
@dr-dimitru contributor agreement received, thanks! 

You can rebase and force push to squash in pull requests, but I noticed GitHub also added the possibility to do this easily form the GUI, so I went ahead and did it.

Btw. in the future you should PR against stable, not master :)

**Comment by dr-dimitru** [comment]
> Btw. in the future you should PR against stable, not master :)

Thank you for mentioning this, from [this doc](https://github.com/phusion/passenger/blob/stable-5.1/CONTRIBUTING.md#git-structure) I decided what it should be sent to `master` branch.

**Comment by OnixGH** [comment]
Hmm, well the doc specifically mentions: "so it is easiest if you submit pull requests to the stable branches", but I can see how opening up with talk about master is confusing, I'll have a look at improving that :)

**Pull request merged**
