### PR TITLE
Add base64 as a dependency

### PR DESCRIPTION
**Pull request by p8**
Ruby 3.4 removes base64 as a default gem.
https://github.com/ruby/ruby/pull/9550

### CODE REVIEW

**Comment by p8** [comment]
Maybe the removal of base64 will be reverted: https://bugs.ruby-lang.org/issues/20859

**Comment by CamJN** [comment]
The revert of removing base64 was rejected. Can you please sign the [contributor agreement](https://www.phusion.nl/contributor) if you haven't done so before.

**Comment by CamJN** [comment]
This was fixed separately by @FooBarWidget

**Comment by p8** [comment]
Sorry, I never got around signing the contributor agreement.
Thanks fixing it!

**Pull request closed without merging**
