### PR TITLE
Fix apache passenger show version in header

### LINKED ISSUE #1638: Apache: PassengerShowVersionInHeader is broken and undocumented
The PassengerShowVersionInHeader option for Apache is accepted, but does not work and is undocumented.

### PR DESCRIPTION
**Pull request by swelther**
The `PassengerShowVersionInHeader off` option is currently not working in Apache (and not documented, to be fair). It works in nginx and most of the code is already there so I made a fix to make it work in Apache too.

Added a small test to prove the new behaviour (TDD & vagrant :heart:).

Fixes #1638

PR for the documentation update: https://github.com/phusion/passenger_library/pull/55

### CODE REVIEW

**Comment by swelther** [comment]
Ah I almost forgot: Would be happy to sign the contributor agreement, but the link is dead: https://www.phusion.nl/forms/contributor_agreement

Can anybody point me to the current version?

**Comment by OnixGH** [comment]
Sorry about that, the link changed after a recent site update. I [fixed this](https://github.com/phusion/passenger/commit/d46325c9f92069b8bc0ab920817ad2855c1e9218) now with the [new link](https://www.phusion.nl/contributor).

**Comment by swelther** [comment]
Thanks, just signed the agreement :grinning:

**Comment by CamJN** [comment]
Hi @swelther, It would be great if you could add a test for when the setting is on as well.

**Comment by swelther** [comment]
@CamJN of course, just pushed it.

Didn't do in the beginning because its default option is on and that is tested by the shared example. Somehow I didn't think about it, thanks :)

**Comment by CamJN** [comment]
This looks good, how would you like your name to appear in the contributors doc?

**Comment by CamJN** [comment]
I can land this if you squash your commits, otherwise I'll get around to it next week. Thanks for putting in the time to contribute. You're awesome!

**Comment by swelther** [comment]
My full name `Sebastian Welther` is totally sufficient :)

Squash is on the way!

**Comment by swelther** [comment]
The link to the moved documentation might need to be adapted when it is available as I'm not sure how the last part will be. Just as an reminder :wink:

**Pull request merged**
