### PR TITLE
Do not hardcode bash(1) location

### PR DESCRIPTION
**Pull request by smortex**
Hardcoding `bash(1)` location is not portable.  Better rely on `env(1)` for finding `bash(1)` in `$PATH`.

For more details about this, you can refer to the wikipedia article about [shebang portability](https://en.wikipedia.org/wiki/Shebang_%28Unix%29#Portability).

### CODE REVIEW

**Comment by FooBarWidget** [comment]
Thanks for your pull request, but all the files you edited are scripts used in CI and testing. All our CI and testing environments have bash in /bin.

**Comment by OnixGH** [comment]
@smortex did you run into an issue with the original code?

On the downside, the (more portible) env-based code is also theorethically slightly more sensitive to code injection.

**Comment by smortex** [comment]
Hi!

In fact, the problems come each time passenger is build on FreeBSD through the ports system: we have sanity checkers that are triggered because the package contain files with invalid shebangs:
https://packages.blogreen.org/data/10_3_RELEASE_amd64-default/2017-12-04_17h25m29s/logs/errors/rubygem-passenger-5.1.12.log

We do have some [tricks to fix these shebangs in the ports tree](https://svnweb.freebsd.org/ports/head/www/nginx/Makefile?revision=455088&view=markup&pathrev=455088#l903), but it fails at detecting and fixing scripts without extension (the two failing files are called `run` in our case).

While we can add some more local settings into the FreeBSD port, I was thinking that using portable shebangs would be adviseable :wink: .

**Comment by FooBarWidget** [comment]
@OnixGH I don't think we'll run into any trouble with these changes. Our CI and testing environments all have bash in PATH and code injection isn't an issue there.

**Pull request merged**
