### PR TITLE
Configurable spawn dir for CageFS (GH-2145)

### PR DESCRIPTION
**Pull request by plmnikulin**
Add Apache

    InstanceRegistryDir /run/passenger/registry

and Nginx

    passenger_spawn_dir /run/passenger/spawn;

configuration options to set spawn directory used during handshake. Hardcoded /tmp is unacceptable for CloudLinux servers with enabled CageFS. Full support would require per-user directories for handshake and registry. Current implementation is a kind of trade-off, it does not allow real illusion of the only user on the server. At least whole /tmp directory should not be exposed to all users.

https://docs.cloudlinux.com/cagefs.html

### CODE REVIEW

**Comment by CamJN** [comment]
In order to accept this PR please sign the [contributor agreement](https://www.phusion.nl/contributor).

**Comment by plmnikulin** [comment]
I have signed the agreement.

**Comment by CamJN** [comment]
Sorry for the delay, I haven't forgotten about this, it's just that the CI is blocked on this currently: https://github.com/rvm/rvm/milestone/41

**Comment by plmnikulin** [comment]
However the patch works for me, I worry a bit that I have missed something that can be easily spotted by everyone familiar with passenger code even without CI.

**Comment by CamJN** [comment]
The changes look good, so no worries there.

**Pull request merged**
