### PR TITLE
Add Compatibility for Rack 3 (Rails > 7.1)

### PR DESCRIPTION
**Pull request by GhaniyKie**
**Bugfix for Ruby Application using Rack 3 (e.g: Rails > 7.1)** [Issues #2508]

This PR fix `Rack::Handler is deprecated and replaced by Rackup::Handler` deprecation warning, `Calling Rackup::Handler.register with a string is deprecated, use the class/module itself`, and `uninitialized constant Rackup::Handler::Rack (NameError)` errors that i face.

### CODE REVIEW

**Comment by CamJN** [comment]
Rack3 is not compatible with Ruby 2.0.0p648, we need to maintain compat back to that version until EL7 is EOL. Can you update the deps to allow but not require Rack 3?

**Comment by GhaniyKie** [comment]
> Rack3 is not compatible with Ruby 2.0.0p648, we need to maintain compat back to that version until EL7 is EOL. Can you update the deps to allow but not require Rack 3?

Sure. I'll try 👍

**Comment by Pimentoso** [comment]
What's the status on this one? At the moment it's not possible to deploy projects that use rails 7.1

**Comment by dmitry** [comment]
Please update passenger gem with this patch.

**Comment by CamJN** [comment]
@dmitry i can’t, we have to support older versions. If it gets updated to be backwards compatible then I can. I also need the contributor agreement signed, [here](https://www.phusion.nl/contributor), if it’s not already done.

**Comment by CamJN** [comment]
@GhaniyKie are you going to work on this further or should I take over?

**Comment by GhaniyKie** [comment]
Yes. You can. 😄
________________________________
Dari: Camden Narzt ***@***.***>
Dikirim: Rabu, 27 Maret 2024 00.03
Kepada: phusion/passenger ***@***.***>
Cc: Abdul Hakim Ghaniy ***@***.***>; Mention ***@***.***>
Subjek: Re: [phusion/passenger] Add Compatibility for Rack 3 (Rails > 7.1) (PR #2507)


@GhaniyKie<https://github.com/GhaniyKie> are you going to work on this further or should I take over?

**Comment by dpneumo** [comment]
Any rough timeline for completion would be useful. However, I understand that is probably not possible. Appreciate the work done here.

**Pull request closed without merging**
