### PR TITLE
implement UnionStation/Context#sendEvent and process spawn event

### PR DESCRIPTION
**Pull request by tinco**
Feedback would be very welcome :)

### CODE REVIEW

**Comment by tinco** [comment]
bump!

**Comment by tinco** [comment]
I forgot, is there a reason this hasn't been pulled in yet? Could anyone review this? It's just a few lines.

**Comment by OnixGH** [comment]
Decided to postpone for now.

**Comment by tinco** [comment]
Is this code really so hard to review? I mean I know C++ is a shitty language, but this is super straightforward isn't it?

**Comment by OnixGH** [comment]
Please refer to internal discussion: it wasn't postponed because of the code (btw. the code isn't super straightforward, e.g. it introduces an entirely new category, but that's besides the point at this time).

**Pull request closed without merging**
