### PR TITLE
patch winston to suppress padLevels warning

### PR DESCRIPTION
**Pull request by distalx**
See [#winstonjs/winston/issues/1882](https://github.com/winstonjs/winston/issues/1882)

This is a fix for #2341 

There are other few changes necessary to keep winston up to date with it's version `2.4.5`.

Hope this helps :)

Edit: 
I've already signed contributor agreement!

cc @CamJN

### CODE REVIEW

**Comment by distalx** [comment]
@CamJN Just floating this on top of your inbox!

**Comment by CamJN** [comment]
Thanks for reminding me to look at this. Would bumping to 2.4.5 work as an alternative approach that keeps our copy of winston the same as upstream?

**Comment by distalx** [comment]
@CamJN

>Would bumping to 2.4.5 work as an alternative approach that keeps our copy of winston the same as upstream?

No, This issue still persists in 2.4.5. But it would be great if you can update the copy of winston to `2.4.5`.
What stopped me from doing is the impression that the phusion-passenger is using a custom or maybe modified version of winston ([see](https://github.com/phusion/passenger/tree/stable-6.0/src/nodejs_supportlib/vendor-copy/winston)). Once you update the winston to `2.4.5`, follow this workaround suggested in this [comment](https://github.com/winstonjs/winston/issues/1882#issuecomment-963535215) and it would work. 


What I've submitted here is a cherry-picked code from winston branch [2.x](https://github.com/winstonjs/winston/commits/2.x/lib/winston). And I've mentioned those PRs in the code. 

For a long-term solution, phusion-passenger should consider updating the winston to its latest version which is v3 ATM.
And that might require significant effort because of breaking changes.

**Comment by CamJN** [comment]
The only changes we made to the vendored winston was removing non-code files and fixing permissions. The content of the module was identical.

**Comment by distalx** [comment]
I see, Then first we should update the winston to 2.4.5 & then apply this [fix](https://github.com/winstonjs/winston/issues/1882#issuecomment-963535215).

**Pull request closed without merging**
