### PR TITLE
Make nginx engine started by standalone stop gracefully

### PR DESCRIPTION
**Pull request by PikachuEXE**
Solves Nginx engine part in #1598 

Tested manually locally
Don't know how to auto-test this

The config path is necessary, not sure about working dir (but harmless to pass it I guess)

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Please let me know if anything else is required

**Comment by CamJN** [comment]
You need to sign the contributor agreement at https://www.phusion.nl/contributor

**Comment by PikachuEXE** [comment]
I have signed the agreement.
What else is needed?

**Comment by PikachuEXE** [comment]
What are the remaining steps to get this merged?
Especially those requiring my action

**Pull request merged**
